language: python

python:
    - 3.3
    - 3.4

install:
    - pip install flake8
    - pip install nose
    - pip install .
    - wget https://github.com/evilsocket/gibson/archive/$GB.tar.gz
    - tar xfv 1.1.0.tar.gz
    - cd gibson-1.1.0
    - cmake . && make
    - ./gibson -c ./debian/etc/gibson/gibson.conf --logfile /tmp/test_gibson.log --unix_socket /tmp/gibson.sock
    - sleep 3
    - cd ../
    - pip install coveralls

script:
- make cov
# checking examples
- >
  for example in $(find $PWD/examples/ -name "*.py"); do
  echo "Running ${example}";
  python3 ${example} || exit 1;
  done;

env:
- GB=1.1.0
- GB=1.2.0

after_success:
    - coveralls
