language: python

python:
    - 3.3
    - 3.4

install:
    - pip install flake8
    - pip install nose
    - pip install .
    - wget https://github.com/evilsocket/gibson/archive/1.0.2.tar.gz
    - tar xfv 1.0.2.tar.gz
    - cd gibson-1.0.2
    - cmake . && make
    - ./gibson -c ./debian/etc/gibson/gibson.conf --logfile /tmp/test_gibson.log --unix_socket /tmp/gibson.sock
    - sleep 3
    - cd ../
    - pip install coveralls

script:
    - make cov

after_success:
    - coveralls
